import Header from "@/components/Header";
import Footer from "@/components/Footer";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import { Inter } from "next/font/google";

import "./globals.css";

const workSans = Work_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});
const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.className}`}>
        <div className="bg-white flex flex-col gap-[100px]">
          <div className="w-[1216px] h-full flex flex-col mx-auto gap-[100px]">
            <Header />
            {children}
          </div>
          <div className="w-full h-full flex flex-col bg-bgColor">
            <div className="w-[1216px] mx-auto">
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
